# -*- coding: utf-8 -*-
"""AI-Powered Job Market Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zepwn2pJP9KYGZcM4oVT15Ifa8VPfqBY
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("ai_job_market_insights.csv")
df.head()

# Step 2: Clean the Job Title column
df['Job_Title'] = df['Job_Title'].fillna('').str.lower()
df['Matched_Role'] = 'Other'  # Default

# Step 3: Define keywords for each role (with backup phrases)
role_keywords = {
    'Data Analyst': ['data analyst', 'data analytics'],
    'Cybersecurity': ['cybersecurity', 'information security', 'infosec'],
    'AI': ['ai', 'artificial intelligence']
}

# Step 4: Applied keyword matching
for role, keywords in role_keywords.items():
    for keyword in keywords:
        df.loc[df['Job_Title'].str.contains(keyword, case=False, na=False), 'Matched_Role'] = role

# Step 5: Count how many jobs matched each role
role_counts = df['Matched_Role'].value_counts()

# Print results
print("Top Job Roles:\n")
print(role_counts)

# Step 6: Plot roles (only those with non-zero values)
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
role_counts.plot(kind='bar', color='lightblue')
plt.title("Most Common Job Roles in the Dataset")
plt.xlabel("Job Role")
plt.ylabel("Number of Postings")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df.to_csv("classified_job_roles.csv", index=False)